 export const mockProduct = 
  {
    error: false,
    message: "Products Retrived Successfully.",
    total: 37,
    data: [
      {
        id: "919",
        row_order: "0",
        name: "Quinoa Bhujia Achari",
        tax_id: "4",
        slug: "quinoa-bhujia-achari",
        category_id: "134",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "SnacksBazaar",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/9656-2023-02-17.jpg",
        other_images: [],
        size_chart: "",
        description:
          "<p>Snack happy with Quinoa Bhujia. Crispy, crunchy &amp; nutritious made from 100% Quinoa. These delicious mouth-watering crunchy balls come packed with high-quality protein, fiber and iron with lip-smacking masala flavor so it not only tastes great but is also great for you!</p>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 03:14:19",
        category_name: "Snacks",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "883",
            product_id: "919",
            price: "100",
            discounted_price: "0",
            serve_for: "Sold Out",
            stock: "0",
            measurement: "100",
            measurement_unit_name: "gm",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "920",
        row_order: "0",
        name: "Masala Puffs",
        tax_id: "4",
        slug: "masala-puffs-1",
        category_id: "134",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "SnacksBazaar",
        made_in: "India",
        return_status: "1",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/2330-2023-02-17.jpg",
        other_images: [],
        size_chart: "",
        description:
          "<p>rispy, crunchy &amp; nutritious made from 100% Quinoa. These delicious mouth-watering crunchy balls come packed with high-quality protein, fiber and iron with lip-smacking masala flavor so it not only tastes great but is also great for you!</p>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 03:17:14",
        category_name: "Snacks",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "884",
            product_id: "920",
            price: "100",
            discounted_price: "0",
            serve_for: "Available",
            stock: "76",
            measurement: "100",
            measurement_unit_name: "gm",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "918",
        row_order: "0",
        name: "Makhana Chips Peri Peri Flavour",
        tax_id: "4",
        slug: "makhana-chips-peri-peri-flavour",
        category_id: "134",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "SnacksBazaar",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/2178-2023-02-17.jpg",
        other_images: [],
        size_chart: "",
        description:
          "<p>Makhana Chips peri peri chips\u00a0are perfect to satisfy your chatpati cravings without compromising on your health. These\u00a0peri peri\u00a0makahans by are specially curated for people who follow a strict fitness diet to keep their health on track. The makhanas are known to be a healthy substitute for regular chips and nachos and a good blend of spices makes them delicious to satisfy your cravings.\u00a0</p>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 03:11:23",
        category_name: "Snacks",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "882",
            product_id: "918",
            price: "100",
            discounted_price: "10",
            serve_for: "Available",
            stock: "11",
            measurement: "100",
            measurement_unit_name: "gm",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "917",
        row_order: "0",
        name: "Murruku - Vacuum fried",
        tax_id: "4",
        slug: "murruku-vacuum-fried",
        category_id: "134",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "SnacksBazaar",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/5075-2023-02-17.jpg",
        other_images: [],
        size_chart: "",
        description:
          "<p>Murukku is a versatile\u00a0vacuum fried and extremely popular anytime snack especially in south India.</p>\r\n<p>They are often served as a tea time snack or even served along with food. Usually, Murukku are not spicy but very flavorful from the cumin seeds and asafoetida, crunchy and delicious snack.</p>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 03:08:31",
        category_name: "Snacks",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "881",
            product_id: "917",
            price: "100",
            discounted_price: "10",
            serve_for: "Available",
            stock: "24",
            measurement: "100",
            measurement_unit_name: "gm",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "916",
        row_order: "0",
        name: "Vacuum Fried Banana Chips",
        tax_id: "4",
        slug: "vacuum-fried-banana-chips",
        category_id: "134",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "SnacksBazaar",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/1512-2023-02-17.jpg",
        other_images: [],
        size_chart: "",
        description:
          '<div class="rawDataLine"><strong><span class="labelText">Banana Chips (Salt &amp; Pepper Flavoured)</span></strong></div>\r\n<div class="rawDataLine">\u00a0</div>\r\n<div class="rawDataLine"><span class="labelText">Kerala banana chips are really special because of its taste, texture, and experience it provides. The secret behind all the above attributes is the variety of banana used for making chips. it is an exclusive variety of banana called Nendran that grows in Kerala. Its thick flesh with rich in fiber is perfect for banana chips</span></div>',
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 03:07:02",
        category_name: "Snacks",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "880",
            product_id: "916",
            price: "100",
            discounted_price: "10",
            serve_for: "Available",
            stock: "13",
            measurement: "100",
            measurement_unit_name: "gm",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "915",
        row_order: "0",
        name: "Oats Chips - Sour Cream & Onion",
        tax_id: "4",
        slug: "oats-chips-sour-cream-onion",
        category_id: "134",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "SnacksBazaar",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/8176-2023-02-17.jpg",
        other_images: [],
        size_chart: "",
        description:
          '<p style="font-weight: 400;">\u00a0The goodness of oats, Urad Dal &amp; nutritious rice assorted with spices is what makes this an ultimate ANYTIME DIET SNACK. This protein-rich snack boosts your energy &amp; helps in your digestive process. Say hello to a happier and healthier you.</p>\r\n<p style="font-weight: 400;"><strong>HEALTH BENEFITS:\u00a0</strong></p>\r\n<ul style="font-weight: 400;">\r\n<li>High in fibre, which helps in lowering down the cholesterol level.</li>\r\n<li>This incredible snack mix is super heart healthy.</li>\r\n<li>Helps with Weight Loss.</li>\r\n<li>Help maintain appropriate blood pressure levels.</li>\r\n<li>Provide a healthy digestive system.</li>\r\n</ul>\r\n<p style="font-weight: 400;"><strong>INGREDIENTS:\u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0 \u00a0<br /></strong>Oats Flour, Urad dal flour, rice flour, Starch,\u00a0Rice Bran oil, salt &amp; spices.</p>',
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 02:47:05",
        category_name: "Snacks",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "879",
            product_id: "915",
            price: "100",
            discounted_price: "9",
            serve_for: "Available",
            stock: "37",
            measurement: "100",
            measurement_unit_name: "gm",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "914",
        row_order: "0",
        name: "Baked Bhakarwadi",
        tax_id: "4",
        slug: "baked-bhakarwadi",
        category_id: "134",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "SnacksBazaar",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/0824-2023-02-17.jpg",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676626974.1847-166.jpg",
        ],
        size_chart: "",
        description:
          '<p><span style="font-family: Arial;">Bringing to you Maharashtra\'s favorite\u00a0tea time snack. Traditionally Bhakarwadi is deep fried making it a more unhealthy. Our crunchy Bhakarwadi comes baked with goodness of spices to satisfy your tea time hunger and giving your taste buds the flavors of different spices along with sweetness and tanginess.</span></p>\r\n<p><span style="font-family: Arial;"><u><strong>INGREDIENTS:</strong></u><u><br /></u></span></p>\r\n<p><span style="font-family: Arial;">Gram Flour, Sugar, Spices, Rice Bran Oil, Iodized\u00a0Salt, Refined Flour, Condiments &amp; Citric Acid</span></p>',
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 02:42:54",
        category_name: "Snacks",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "878",
            product_id: "914",
            price: "100",
            discounted_price: "10",
            serve_for: "Available",
            stock: "6",
            measurement: "100",
            measurement_unit_name: "gm",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "913",
        row_order: "0",
        name: "Soya Corn Chips",
        tax_id: "4",
        slug: "soya-corn-chips",
        category_id: "134",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "SnacksBazaar",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/6432-2023-02-17.jpg",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676626863.0042-161.jpg",
        ],
        size_chart: "",
        description:
          "<p>Behold the snack you\u2019ll find super hard to keep your hands off, these soya corn chips offer a unique blend of taste and nourishment. They are a healthier alternative to the regular fried chips, and they taste great too. \u00a0\u00a0 \u00a0</p>\r\n<p><u><strong>HEALTH BENEFITS</strong></u></p>\r\n<ul>\r\n<li>Gets easily digested, hence does no harm to the digestive system.\u00a0</li>\r\n<li>Maintains cholesterol levels.\u00a0</li>\r\n<li>Enhances immunity.\u00a0</li>\r\n<li>A healthy alternative to curb mid-meal hunger pang.\u00a0</li>\r\n<li>Heart healthy.\u00a0</li>\r\n<li>Regulates satiety hormone.\u00a0 \u00a0</li>\r\n</ul>\r\n<p><u><strong>INGREDIENTS:</strong></u><br />Soya flour, corn flour, seasoning</p>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 02:41:03",
        category_name: "Snacks",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "877",
            product_id: "913",
            price: "100",
            discounted_price: "10",
            serve_for: "Available",
            stock: "52",
            measurement: "100",
            measurement_unit_name: "gm",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "883",
        row_order: "0",
        name: "Hypnotic Red Roses Box",
        tax_id: "0",
        slug: "hypnotic-red-roses-box-1",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/2174-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676617163.6588-579.png",
        ],
        size_chart: "",
        description:
          "<p><strong>Product Details:</strong></p>\r\n<ul>\r\n<li><strong>Flower Type:</strong>\u00a0Red Roses</li>\r\n<li><strong>No of Flower:</strong>\u00a06 Sticks</li>\r\n<li><strong>Packing:</strong>\u00a0Gift box</li>\r\n<li><strong>Bow:</strong>\u00a0Red\u00a0Ribbon</li>\r\n</ul>\r\n<p><strong>Delivery Information:</strong></p>\r\n<ul>\r\n<li>Only for reference purposes is the product shown in the picture.</li>\r\n<li>Depending on what's available, the shape and design of the final product may change.</li>\r\n<li>Your order won't be delivered elsewhere; it will be sent to the address you provide.</li>\r\n<li>Flowers may be provided as blooms, semi-blooms, or buds.</li>\r\n<li>The two different orders placed with our portal won't come at the same time.</li>\r\n</ul>\r\n<p><strong>Care Instructions:</strong></p>\r\n<ul>\r\n<li>Keep flowers away from direct sunlight.\u00a0</li>\r\n<li>Remove the damaged petals from the flowers.\u00a0</li>\r\n<li>Make sure that the flower form remains soaked in water.\u00a0</li>\r\n<li>A daily mist of water is beneficial for flowers.</li>\r\n</ul>\r\n<p><strong>Please Note:</strong></p>\r\n<ul>\r\n<li>Non-woven fabric wrapping is replaced with paper wrapping in Bangalore, Mumbai, Pune, and other cities as per government rule.</li>\r\n<li>Green fillers may vary per availability according to the season.</li>\r\n<li>Bow color according to the availability</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-16 23:59:23",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "847",
            product_id: "883",
            price: "550",
            discounted_price: "500",
            serve_for: "Available",
            stock: "13",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "885",
        row_order: "0",
        name: "Attractive Mixed Lilies",
        tax_id: "0",
        slug: "attractive-mixed-lilies-1",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "1",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/6875-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676617492.8528-742.png",
        ],
        size_chart: "",
        description:
          "<p>Send this Attractive Mixed 8 Lilies bouquet to your loved one who is not with you at the moment. Wish them a happy and healthy life with this beauty.</p>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:04:52",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "849",
            product_id: "885",
            price: "1000",
            discounted_price: "950",
            serve_for: "Available",
            stock: "6",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "884",
        row_order: "0",
        name: "Vibrant Blue Orchids",
        tax_id: "0",
        slug: "vibrant-blue-orchids",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/3877-2023-02-17.png",
        other_images: [],
        size_chart: "",
        description:
          "<p><strong>Product Details:</strong></p>\r\n<ul>\r\n<li><strong>Flower Type:</strong>\u00a0Blue Orchids\u00a0</li>\r\n<li><strong>No of Flower:</strong>\u00a06</li>\r\n<li><strong>Fillers:\u00a0</strong>Seasonal Fillers</li>\r\n<li><strong>Packing:</strong>\u00a02 Layer Sky-blue &amp; White Paper Packing</li>\r\n<li><strong>Bow:</strong>\u00a0Blue\u00a0Ribbon</li>\r\n</ul>\r\n<p><strong>Delivery Information</strong></p>\r\n<ul>\r\n<li>The product shown in the image is for reference purposes only.\u00a0</li>\r\n<li>The actual product may vary in shape/design and depending on availability.\u00a0</li>\r\n<li>The product will be delivered to the specified address and won't be shipped elsewhere.\u00a0</li>\r\n<li>The delivery of Flowers may be in the form of blooms or semi or buds.\u00a0</li>\r\n<li>Two separate orders via our portal may arrive at the same time.</li>\r\n</ul>\r\n<p><strong>Care Instructions</strong></p>\r\n<ul>\r\n<li>Keep flowers away from direct sunlight.</li>\r\n<li>Remove the damaged petals from the flowers.</li>\r\n<li>Make sure that the flower form remains soaked in water.</li>\r\n<li>A daily mist of water is beneficial for flowers.</li>\r\n</ul>\r\n<p><strong>Please Note:</strong></p>\r\n<ul>\r\n<li>As per government rule, non-woven fabric wrapping will be replaced by paper wrapping in Bangalore, Mumbai, Pune, and other cities where non-woven fabric wrapping is prohibited.\u00a0\u00a0</li>\r\n<li>Green fillers may vary as per the availability\u00a0\u00a0</li>\r\n<li>Bow color according to the availability</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:02:05",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "848",
            product_id: "884",
            price: "1200",
            discounted_price: "1100",
            serve_for: "Sold Out",
            stock: "0",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "886",
        row_order: "0",
        name: "Forever Blossom Bouquet",
        tax_id: "0",
        slug: "forever-blossom-bouquet",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/5373-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676617693.6141-717.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/7566-2023-02-17.png",
        description:
          "<p>Valentine's day is coming soon when you can please your sweetie with an extraordinary gift. So, try this attractive bouquet of pink gerberas and yellow roses in two-layer packing to mark this special day. Order now!</p>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:08:13",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "850",
            product_id: "886",
            price: "599",
            discounted_price: "580",
            serve_for: "Available",
            stock: "37",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "887",
        row_order: "0",
        name: "Celestial Carnations Jute Bouquet",
        tax_id: "0",
        slug: "celestial-carnations-jute-bouquet",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/1270-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676617767.6261-192.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/5881-2023-02-17.png",
        description:
          "<p>Celestial Carnations Jute Bouquet is a perfect floral gift to charm your beloved partner this upcoming Valentine's Day. Then you have the best option online at the Winni portal with a natural jute packing arrangement of fresh red carnations to show your deep affection. Order now!</p>",
        shipping_delivery: "",
        status: "1",
        ratings: "4.0",
        number_of_ratings: "1",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:09:27",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "851",
            product_id: "887",
            price: "799",
            discounted_price: "770",
            serve_for: "Available",
            stock: "29",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "888",
        row_order: "0",
        name: "Belgium Chocolate Truffle Cake",
        tax_id: "4",
        slug: "belgium-chocolate-truffle-cake",
        category_id: "46",
        subcategory_id: "161",
        indicator: "1",
        manufacturer: "Cakes Worlds",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/5323-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676617809.0695-140.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/1246-2023-02-17.png",
        description:
          "<ul>\r\n<li>Cake Flavour: Belgium Chocolate Truffle</li>\r\n<li>Shape:\u00a0Square</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Chocolate</li>\r\n<li>Type of cream: Truffle</li>\r\n<li>Filling in Layers: Belgium Chocolate Truffle</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:10:09",
        category_name: " Cakes",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "852",
            product_id: "888",
            price: "800",
            discounted_price: "200",
            serve_for: "Sold Out",
            stock: "0",
            measurement: "500",
            measurement_unit_name: "gm",
            stock_unit_name: "gm",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "899",
        row_order: "0",
        name: "Light Yummy Chocolate Cake",
        tax_id: "4",
        slug: "light-yummy-chocolate-cake",
        category_id: "46",
        subcategory_id: "162",
        indicator: "1",
        manufacturer: "Cakes mart",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/5798-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676619164.7415-503.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/2292-2023-02-17.png",
        description:
          "<ul>\r\n<li>Cake Flavour: Light Chocolate</li>\r\n<li>Shape: Round</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Chocolate</li>\r\n<li>Type of Cream: Chocolate</li>\r\n<li>Filling in Layers: Chocolate Chip</li>\r\n<li>Topping: Chocolate Garnish With Ribbon</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:32:44",
        category_name: " Cakes",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "863",
            product_id: "899",
            price: "1000",
            discounted_price: "100",
            serve_for: "Available",
            stock: "34",
            measurement: "500",
            measurement_unit_name: "gm",
            stock_unit_name: "gm",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "890",
        row_order: "0",
        name: "Decorated Hidden Gems Cake",
        tax_id: "4",
        slug: "decorated-hidden-gems-cake",
        category_id: "46",
        subcategory_id: "162",
        indicator: "1",
        manufacturer: "Cakes Worlds",
        made_in: "India",
        return_status: "1",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/4825-2023-02-17.jpeg",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676618077.6626-465.jpeg",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/7619-2023-02-17.jpeg",
        description:
          "<ul>\r\n<li>Cake Flavor- Decorated Hidden Gems Cake</li>\r\n<li>Type of Cake- Cream Cake</li>\r\n<li>Weight- Half Kg</li>\r\n<li>Shape- Round</li>\r\n<li>Serves- 4-6 People</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:14:37",
        category_name: " Cakes",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "854",
            product_id: "890",
            price: "1000",
            discounted_price: "100",
            serve_for: "Available",
            stock: "37",
            measurement: "500",
            measurement_unit_name: "gm",
            stock_unit_name: "gm",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "891",
        row_order: "0",
        name: "Choco Chip Muddy Chocolate Cake",
        tax_id: "4",
        slug: "choco-chip-muddy-chocolate-cake",
        category_id: "46",
        subcategory_id: "161",
        indicator: "1",
        manufacturer: "Cakes mart",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/3804-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676618218.9104-303.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/1882-2023-02-17.png",
        description:
          "<ul>\r\n<li>Cake Flavour: Chocolate</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Chocolate</li>\r\n<li>Type of Cream: Chocolate</li>\r\n<li>Filling in Layers: Chocochip</li>\r\n<li>Toppings: Chocochip &amp; Chocolate garnish</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:16:58",
        category_name: " Cakes",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "855",
            product_id: "891",
            price: "1200",
            discounted_price: "300",
            serve_for: "Sold Out",
            stock: "0",
            measurement: "500",
            measurement_unit_name: "gm",
            stock_unit_name: "gm",
            images: [
              "http://grocery.intelliatech.com/upload/variant_images/1676618218.9123-951.png",
            ],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "892",
        row_order: "0",
        name: "Marble Crunch Cake",
        tax_id: "4",
        slug: "marble-crunch-cake",
        category_id: "46",
        subcategory_id: "161",
        indicator: "1",
        manufacturer: "Cakes mart",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/8672-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676618331.2963-321.png",
        ],
        size_chart: "",
        description:
          "<ul>\r\n<li>Cake Flavour: Chocolate</li>\r\n<li>Shape: Round</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Chocolate</li>\r\n<li>Type of cream: Chocolate</li>\r\n<li>Filling in Layers: Choco Chips</li>\r\n<li>Toppings: White and Chocolate Choco chips, Chocolate,Truffle and Cherry</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:18:51",
        category_name: " Cakes",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "856",
            product_id: "892",
            price: "1000",
            discounted_price: "200",
            serve_for: "Available",
            stock: "7",
            measurement: "500",
            measurement_unit_name: "gm",
            stock_unit_name: "gm",
            images: [
              "http://grocery.intelliatech.com/upload/variant_images/1676618331.2981-683.png",
            ],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "893",
        row_order: "0",
        name: "Butterscotch Flavorsome Cake",
        tax_id: "4",
        slug: "butterscotch-flavorsome-cake",
        category_id: "46",
        subcategory_id: "161",
        indicator: "1",
        manufacturer: "Cakes mart",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/7838-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676618514.4507-128.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/6133-2023-02-17.png",
        description:
          "<ul>\r\n<li>Cake Flavor: Butterscotch</li>\r\n<li>Shape: Round</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Vanilla</li>\r\n<li>Type of cream: Vanilla</li>\r\n<li>Filling in Layers: Butterscotch</li>\r\n<li>Toppings: Butterscotch, Cherry, chocolate &amp; Choco Chip</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:21:54",
        category_name: " Cakes",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "857",
            product_id: "893",
            price: "800",
            discounted_price: "50",
            serve_for: "Available",
            stock: "29",
            measurement: "500",
            measurement_unit_name: "gm",
            stock_unit_name: "gm",
            images: [
              "http://grocery.intelliatech.com/upload/variant_images/1676618514.4521-883.png",
            ],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "894",
        row_order: "0",
        name: "Fantasy Mix Gerbera",
        tax_id: "0",
        slug: "fantasy-mix-gerbera",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/0536-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676618547.3461-118.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/7798-2023-02-17.png",
        description:
          "<p>A beautiful floral collection is here to surprise your near or dear ones. Here you will get white Gerberas and yellow gerberas in a perfect floral arrangement to complement the recipient. Order Now!</p>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:22:27",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "858",
            product_id: "894",
            price: "799",
            discounted_price: "780",
            serve_for: "Available",
            stock: "67",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "895",
        row_order: "0",
        name: "Pink Gerbera Flowers",
        tax_id: "0",
        slug: "pink-gerbera-flowers",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/7845-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676618638.5241-705.png",
        ],
        size_chart: "",
        description:
          "<p><strong>Product Details:</strong></p>\r\n<ul>\r\n<li>Flower Type: \u00a0Pink Gerberas</li>\r\n<li>No of Flower: 12</li>\r\n<li>Fillers: Seasonal Filers\u00a0</li>\r\n<li>Packing: 2 Layer Blue Paper Packing</li>\r\n<li>Bow:\u00a0\u00a0Pink Ribbon</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:23:58",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "859",
            product_id: "895",
            price: "899",
            discounted_price: "870",
            serve_for: "Available",
            stock: "52",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "896",
        row_order: "0",
        name: "Smile Of Lilles",
        tax_id: "0",
        slug: "smile-of-lilles",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/3957-2023-02-17.png",
        other_images: [],
        size_chart: "",
        description:
          "<ul>\r\n<li>5 Lilies</li>\r\n<li>3 Blue Orchids</li>\r\n<li>Glass Vase Arrangement</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:25:16",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "860",
            product_id: "896",
            price: "1399",
            discounted_price: "1380",
            serve_for: "Available",
            stock: "55",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "897",
        row_order: "0",
        name: "Blossomy Attraction",
        tax_id: "0",
        slug: "blossomy-attraction",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/7278-2023-02-17.jpg",
        other_images: [],
        size_chart: "",
        description:
          "<p>\u00a0</p>\r\n<ul>\r\n<li>Flower Type: 4 Red Roses+2 Yellow Lilies+1 White\u00a0 Gladiolus</li>\r\n<li>No of Flower: 7</li>\r\n<li>Fillers: Seasonal Fillers</li>\r\n<li>Base:\u00a0Glass Vase</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:26:30",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "861",
            product_id: "897",
            price: "1499",
            discounted_price: "1478",
            serve_for: "Available",
            stock: "43",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "898",
        row_order: "0",
        name: "Yellow Roses Bunch",
        tax_id: "0",
        slug: "yellow-roses-bunch",
        category_id: "132",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/6992-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676618890.6746-450.png",
        ],
        size_chart: "",
        description:
          "<ul>\r\n<li>18 Yellow Roses</li>\r\n<li>Yellow Paper Wrapping</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:28:10",
        category_name: "Flowers",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "862",
            product_id: "898",
            price: "1299",
            discounted_price: "1280",
            serve_for: "Available",
            stock: "23",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "900",
        row_order: "0",
        name: "Ferrero Rocher Chocolate Bouquet",
        tax_id: "0",
        slug: "ferrero-rocher-chocolate-bouquet-1",
        category_id: "133",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/1690-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676619570.0477-921.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/2918-2023-02-17.png",
        description:
          "<ul>\r\n<li>Chocolate: Ferrero Rochers\u00a0</li>\r\n<li>No of Chocolate: 10</li>\r\n<li>Packing:\u00a02 Layer Golden Paper Packing</li>\r\n<li>Bow:\u00a0Golden Ribbon</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:39:30",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "864",
            product_id: "900",
            price: "1199",
            discounted_price: "1180",
            serve_for: "Sold Out",
            stock: "0",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "901",
        row_order: "0",
        name: "Rosy Pista Cream Cake",
        tax_id: "4",
        slug: "rosy-pista-cream-cake-1",
        category_id: "46",
        subcategory_id: "162",
        indicator: "1",
        manufacturer: "Cakes mart",
        made_in: "India",
        return_status: "1",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/0460-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676619833.538-783.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/5486-2023-02-17.png",
        description:
          "<ul>\r\n<li>Cake Flavour: Rasmalai</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Vanilla</li>\r\n<li>Type of cream: Vanilla</li>\r\n<li>Filling in Layers: Rasmalai Vanilla cream</li>\r\n<li>Toppings: Rasmalai</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "4.0",
        number_of_ratings: "2",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:43:53",
        category_name: " Cakes",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "865",
            product_id: "901",
            price: "900",
            discounted_price: "90",
            serve_for: "Sold Out",
            stock: "0",
            measurement: "500",
            measurement_unit_name: "gm",
            stock_unit_name: "gm",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "902",
        row_order: "0",
        name: "Dairy Milk Chocolate Basket",
        tax_id: "0",
        slug: "dairy-milk-chocolate-basket-1",
        category_id: "133",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "1",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/4779-2023-02-17.jpg",
        other_images: [],
        size_chart: "",
        description:
          "<ul>\r\n<li>Chocolate: Dairy Milk chocolate (13 gm each)</li>\r\n<li>No of Chocolate: 10</li>\r\n<li>Packing: Blue Net Packing</li>\r\n<li>Base: Wooden Basket</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "3.0",
        number_of_ratings: "1",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:44:55",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "866",
            product_id: "902",
            price: "599",
            discounted_price: "140",
            serve_for: "Available",
            stock: "959",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: true,
            flash_sales: [
              {
                price: "599",
                discounted_price: "580",
                start_date: "2023-02-17 15:30:10",
                end_date: "2023-02-27 15:30:16",
                is_start: true,
              },
            ],
          },
        ],
      },
      {
        id: "903",
        row_order: "0",
        name: "Choco Strawberry Cake",
        tax_id: "4",
        slug: "choco-strawberry-cake-1",
        category_id: "46",
        subcategory_id: "162",
        indicator: "1",
        manufacturer: "Cakes mart",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/6033-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676619920.012-755.png",
        ],
        size_chart: "",
        description:
          "<ul>\r\n<li>Cake Flavour: Choco Fusion Cake (Chocolate, Strawberry)</li>\r\n<li>Shape: Round</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Vanilla</li>\r\n<li>Type of cream: Strawberry Vanilla</li>\r\n<li>Filling in Layers: Strawberry Vanilla</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:45:20",
        category_name: " Cakes",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "867",
            product_id: "903",
            price: "699",
            discounted_price: "100",
            serve_for: "Available",
            stock: "6",
            measurement: "500",
            measurement_unit_name: "gm",
            stock_unit_name: "pack",
            images: [
              "http://grocery.intelliatech.com/upload/variant_images/1676619920.0145-711.png",
            ],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "904",
        row_order: "0",
        name: "Cashew KitKat Oreo Dream Drip Cake",
        tax_id: "4",
        slug: "cashew-kitkat-oreo-dream-drip-cake",
        category_id: "46",
        subcategory_id: "161",
        indicator: "1",
        manufacturer: "Cakes mart",
        made_in: "India",
        return_status: "1",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/3769-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676620056.664-560.png",
        ],
        size_chart: "",
        description:
          "<ul>\r\n<li>Cake Flavour: Chocolate</li>\r\n<li>Shape: Round</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Vanilla</li>\r\n<li>Type of Cream:\u00a0Chocolate</li>\r\n<li>Filling In Layers: Vanilla Cream</li>\r\n<li>Toppings: Crush Cashew, Oreo, Kitkat &amp; Sprinkle Garnish</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:47:36",
        category_name: " Cakes",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "868",
            product_id: "904",
            price: "599",
            discounted_price: "69",
            serve_for: "Sold Out",
            stock: "0",
            measurement: "500",
            measurement_unit_name: "gm",
            stock_unit_name: "gm",
            images: [
              "http://grocery.intelliatech.com/upload/variant_images/1676620056.6663-126.png",
            ],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "905",
        row_order: "0",
        name: "Heart Shaped Sweet Chocolate Box",
        tax_id: "0",
        slug: "heart-shaped-sweet-chocolate-box-1",
        category_id: "133",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/5304-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676620062.1734-608.png",
        ],
        size_chart:
          "http://grocery.intelliatech.com/upload/images/6914-2023-02-17.png",
        description:
          "<ul>\r\n<li>Number of Chocolates- 6 Pcs\u00a0</li>\r\n<li>Shape of Chocolates- 4 Heart-Shaped, 2 Rose Shaped\u00a0</li>\r\n<li>Type of Chocolates- White &amp; Milk Chocolate\u00a0</li>\r\n<li>Chocolate Weight- 60 gms</li>\r\n<li>Box Dimensions- 18*13*5</li>\r\n<li>Occasion Type- The chocolates can be gifted on Valentine's, anniversary, birthday or any special occasion</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:47:42",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "869",
            product_id: "905",
            price: "299",
            discounted_price: "270",
            serve_for: "Sold Out",
            stock: "0",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "906",
        row_order: "0",
        name: "Artisanal Dark Sugar Free Chocolate Bar",
        tax_id: "0",
        slug: "artisanal-dark-sugar-free-chocolate-bar",
        category_id: "133",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/2877-2023-02-17.png",
        other_images: [],
        size_chart: "",
        description:
          "<ul>\r\n<li>Sugarfree Chocolates</li>\r\n<li>Weight :\u00a0460 gm</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:49:34",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "870",
            product_id: "906",
            price: "999",
            discounted_price: "980",
            serve_for: "Available",
            stock: "32",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "907",
        row_order: "0",
        name: "Yummilicious Chocolates",
        tax_id: "4",
        slug: "yummilicious-chocolates",
        category_id: "133",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "ChoaclateIndia",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/1554-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676620737.7294-106.png",
        ],
        size_chart: "",
        description:
          "<ul>\r\n<li>5 silk</li>\r\n<li>5 Kitkat</li>\r\n<li>5 Dairy Milk</li>\r\n<li>Small Ferrero Rochers</li>\r\n<li>5 Gems Packet</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:58:57",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "871",
            product_id: "907",
            price: "500",
            discounted_price: "100",
            serve_for: "Available",
            stock: "91",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: true,
            flash_sales: [
              {
                price: "500",
                discounted_price: "100",
                start_date: "2023-02-17 15:30:10",
                end_date: "2023-02-27 15:30:16",
                is_start: true,
              },
            ],
          },
        ],
      },
      {
        id: "908",
        row_order: "0",
        name: "Show Your Passion",
        tax_id: "0",
        slug: "show-your-passion",
        category_id: "133",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/6560-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676620780.0278-814.png",
        ],
        size_chart: "",
        description:
          "<ul>\r\n<li>Chocolate: Big Ferrero Rochers Box</li>\r\n<li>Chocolate: 1 Silk Chocolate+3 Kitkat Chocolates</li>\r\n<li>No of Chocolate: 4 Pcs+ 1 Box</li>\r\n<li>Packing: Paper Packing</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 00:59:40",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "872",
            product_id: "908",
            price: "1399",
            discounted_price: "1350",
            serve_for: "Available",
            stock: "49",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "909",
        row_order: "0",
        name: "Futuristic Lover",
        tax_id: "4",
        slug: "futuristic-lover",
        category_id: "133",
        subcategory_id: "0",
        indicator: "1",
        manufacturer: "chocolateIndia",
        made_in: "India",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/0248-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676620837.0816-972.png",
        ],
        size_chart: "",
        description:
          "<ul>\r\n<li>Chocolate: 3 Silk Chocolate+3 5star Chocolates</li>\r\n<li>Box: Small Ferrero Rochers</li>\r\n<li>No of Chocolate: 6pcs+1Box</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 01:00:37",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "873",
            product_id: "909",
            price: "400",
            discounted_price: "40",
            serve_for: "Available",
            stock: "120",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "kg",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "910",
        row_order: "0",
        name: "Two Layer Assorted Chocolate Arrangement",
        tax_id: "0",
        slug: "two-layer-assorted-chocolate-arrangement",
        category_id: "133",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/0154-2023-02-17.png",
        other_images: [
          "http://grocery.intelliatech.com/upload/other_images/1676620854.1617-267.png",
        ],
        size_chart: "",
        description:
          "<ul>\r\n<li><strong>Chocolate:\u00a0</strong>10 Dairy Milk Chocolates+20 5-Star Chocolate</li>\r\n<li><strong>No of Chocolate:</strong>\u00a030</li>\r\n<li><strong>Base:\u00a0</strong>Round Oasis/Thermacol Base</li>\r\n<li><strong>Fillers:</strong>\u00a0 Seasonal Fillers</li>\r\n<li>Bow:\u00a0Golden Ribbon</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 01:00:54",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "874",
            product_id: "910",
            price: "560",
            discounted_price: "550",
            serve_for: "Available",
            stock: "42",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "911",
        row_order: "0",
        name: "Artisanal Palm Sugar Dark Chocolate Bar Set Of 2",
        tax_id: "0",
        slug: "artisanal-palm-sugar-dark-chocolate-bar-set-of-2",
        category_id: "133",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/2955-2023-02-17.png",
        other_images: [],
        size_chart: "",
        description:
          "<ul>\r\n<li>Sugarfree Chocolates</li>\r\n<li>Weight : 80 gm</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 01:02:09",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "875",
            product_id: "911",
            price: "699",
            discounted_price: "670",
            serve_for: "Available",
            stock: "31",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
      {
        id: "912",
        row_order: "0",
        name: "Kokomae Luxury Chocolate Hamper",
        tax_id: "0",
        slug: "kokomae-luxury-chocolate-hamper",
        category_id: "133",
        subcategory_id: "0",
        indicator: "0",
        manufacturer: "",
        made_in: "",
        return_status: "0",
        cancelable_status: "0",
        till_status: "",
        image:
          "http://grocery.intelliatech.com/upload/images/7888-2023-02-17.png",
        other_images: [],
        size_chart: "",
        description:
          "<ul>\r\n<li>Orange peel-Dark Chocolate with Candied Orange Peel</li>\r\n<li>Chilli-Dark Chocolate with Chilli</li>\r\n<li>Almond and Saffron-Milk Chocolate with Roasted Almond and</li>\r\n</ul>",
        shipping_delivery: "",
        status: "1",
        ratings: "0.0",
        number_of_ratings: "0",
        is_cod_allowed: "1",
        total_allowed_quantity: "0",
        date_added: "2023-02-17 01:03:43",
        category_name: "Chocolate",
        subcategory_name: "",
        tax_title: "",
        tax_percentage: "0",
        is_added_to_cart: false,
        is_favorite: false,
        variants: [
          {
            type: "packet",
            id: "876",
            product_id: "912",
            price: "3999",
            discounted_price: "3950",
            serve_for: "Sold Out",
            stock: "0",
            measurement: "1",
            measurement_unit_name: "pack",
            stock_unit_name: "pack",
            images: [],
            cart_count: "0",
            is_flash_sales: false,
            flash_sales: [
              {
                price: "",
                discounted_price: "",
                start_date: "",
                end_date: "",
                is_start: false,
              },
            ],
          },
        ],
      },
    ]
  }