// export const mockAllData = 
//   {
//     error: false,
//     message: "Products retrieved successfully",
//     total: "37",
//     limit: 10,
//     offset: 0,
//     data: [
//       {
//         id: "883",
//         name: "Hypnotic Red Roses Box",
//         indicator: "0",
//         image:
//           "http://grocery.intelliatech.com/upload/images/2174-2023-02-17.png",
//         ratings: "0.0",
//         number_of_ratings: "0",
//         total_allowed_quantity: "0",
//         slug: "hypnotic-red-roses-box-1",
//         description:
//           "<p><strong>Product Details:</strong></p>\r\n<ul>\r\n<li><strong>Flower Type:</strong>\u00a0Red Roses</li>\r\n<li><strong>No of Flower:</strong>\u00a06 Sticks</li>\r\n<li><strong>Packing:</strong>\u00a0Gift box</li>\r\n<li><strong>Bow:</strong>\u00a0Red\u00a0Ribbon</li>\r\n</ul>\r\n<p><strong>Delivery Information:</strong></p>\r\n<ul>\r\n<li>Only for reference purposes is the product shown in the picture.</li>\r\n<li>Depending on what's available, the shape and design of the final product may change.</li>\r\n<li>Your order won't be delivered elsewhere; it will be sent to the address you provide.</li>\r\n<li>Flowers may be provided as blooms, semi-blooms, or buds.</li>\r\n<li>The two different orders placed with our portal won't come at the same time.</li>\r\n</ul>\r\n<p><strong>Care Instructions:</strong></p>\r\n<ul>\r\n<li>Keep flowers away from direct sunlight.\u00a0</li>\r\n<li>Remove the damaged petals from the flowers.\u00a0</li>\r\n<li>Make sure that the flower form remains soaked in water.\u00a0</li>\r\n<li>A daily mist of water is beneficial for flowers.</li>\r\n</ul>\r\n<p><strong>Please Note:</strong></p>\r\n<ul>\r\n<li>Non-woven fabric wrapping is replaced with paper wrapping in Bangalore, Mumbai, Pune, and other cities as per government rule.</li>\r\n<li>Green fillers may vary per availability according to the season.</li>\r\n<li>Bow color according to the availability</li>\r\n</ul>",
//         status: "1",
//         category_name: "Flowers",
//         tax_percentage: "0",
//         price: "550",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "847",
//             product_id: "883",
//             price: "550",
//             discounted_price: "500",
//             serve_for: "Available",
//             stock: "8",
//             measurement: "1",
//             measurement_unit_name: "pack",
//             stock_unit_name: "pack",
//             images: [],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//       {
//         id: "884",
//         name: "Vibrant Blue Orchids",
//         indicator: "0",
//         image:
//           "http://grocery.intelliatech.com/upload/images/3877-2023-02-17.png",
//         ratings: "0.0",
//         number_of_ratings: "0",
//         total_allowed_quantity: "0",
//         slug: "vibrant-blue-orchids",
//         description:
//           "<p><strong>Product Details:</strong></p>\r\n<ul>\r\n<li><strong>Flower Type:</strong>\u00a0Blue Orchids\u00a0</li>\r\n<li><strong>No of Flower:</strong>\u00a06</li>\r\n<li><strong>Fillers:\u00a0</strong>Seasonal Fillers</li>\r\n<li><strong>Packing:</strong>\u00a02 Layer Sky-blue &amp; White Paper Packing</li>\r\n<li><strong>Bow:</strong>\u00a0Blue\u00a0Ribbon</li>\r\n</ul>\r\n<p><strong>Delivery Information</strong></p>\r\n<ul>\r\n<li>The product shown in the image is for reference purposes only.\u00a0</li>\r\n<li>The actual product may vary in shape/design and depending on availability.\u00a0</li>\r\n<li>The product will be delivered to the specified address and won't be shipped elsewhere.\u00a0</li>\r\n<li>The delivery of Flowers may be in the form of blooms or semi or buds.\u00a0</li>\r\n<li>Two separate orders via our portal may arrive at the same time.</li>\r\n</ul>\r\n<p><strong>Care Instructions</strong></p>\r\n<ul>\r\n<li>Keep flowers away from direct sunlight.</li>\r\n<li>Remove the damaged petals from the flowers.</li>\r\n<li>Make sure that the flower form remains soaked in water.</li>\r\n<li>A daily mist of water is beneficial for flowers.</li>\r\n</ul>\r\n<p><strong>Please Note:</strong></p>\r\n<ul>\r\n<li>As per government rule, non-woven fabric wrapping will be replaced by paper wrapping in Bangalore, Mumbai, Pune, and other cities where non-woven fabric wrapping is prohibited.\u00a0\u00a0</li>\r\n<li>Green fillers may vary as per the availability\u00a0\u00a0</li>\r\n<li>Bow color according to the availability</li>\r\n</ul>",
//         status: "1",
//         category_name: "Flowers",
//         tax_percentage: "0",
//         price: "1200",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "848",
//             product_id: "884",
//             price: "1200",
//             discounted_price: "1100",
//             serve_for: "Sold Out",
//             stock: "0",
//             measurement: "1",
//             measurement_unit_name: "pack",
//             stock_unit_name: "pack",
//             images: [],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//       {
//         id: "885",
//         name: "Attractive Mixed Lilies",
//         indicator: "0",
//         image:
//           "http://grocery.intelliatech.com/upload/images/6875-2023-02-17.png",
//         ratings: "0.0",
//         number_of_ratings: "0",
//         total_allowed_quantity: "0",
//         slug: "attractive-mixed-lilies-1",
//         description:
//           "<p>Send this Attractive Mixed 8 Lilies bouquet to your loved one who is not with you at the moment. Wish them a happy and healthy life with this beauty.</p>",
//         status: "1",
//         category_name: "Flowers",
//         tax_percentage: "0",
//         price: "1000",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "849",
//             product_id: "885",
//             price: "1000",
//             discounted_price: "950",
//             serve_for: "Sold Out",
//             stock: "0",
//             measurement: "1",
//             measurement_unit_name: "pack",
//             stock_unit_name: "pack",
//             images: [],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//       {
//         id: "886",
//         name: "Forever Blossom Bouquet",
//         indicator: "0",
//         image:
//           "http://grocery.intelliatech.com/upload/images/5373-2023-02-17.png",
//         ratings: "0.0",
//         number_of_ratings: "0",
//         total_allowed_quantity: "0",
//         slug: "forever-blossom-bouquet",
//         description:
//           "<p>Valentine's day is coming soon when you can please your sweetie with an extraordinary gift. So, try this attractive bouquet of pink gerberas and yellow roses in two-layer packing to mark this special day. Order now!</p>",
//         status: "1",
//         category_name: "Flowers",
//         tax_percentage: "0",
//         price: "599",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "850",
//             product_id: "886",
//             price: "599",
//             discounted_price: "580",
//             serve_for: "Available",
//             stock: "26",
//             measurement: "1",
//             measurement_unit_name: "pack",
//             stock_unit_name: "kg",
//             images: [],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//       {
//         id: "887",
//         name: "Celestial Carnations Jute Bouquet",
//         indicator: "0",
//         image:
//           "http://grocery.intelliatech.com/upload/images/1270-2023-02-17.png",
//         ratings: "4.0",
//         number_of_ratings: "1",
//         total_allowed_quantity: "0",
//         slug: "celestial-carnations-jute-bouquet",
//         description:
//           "<p>Celestial Carnations Jute Bouquet is a perfect floral gift to charm your beloved partner this upcoming Valentine's Day. Then you have the best option online at the Winni portal with a natural jute packing arrangement of fresh red carnations to show your deep affection. Order now!</p>",
//         status: "1",
//         category_name: "Flowers",
//         tax_percentage: "0",
//         price: "799",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "851",
//             product_id: "887",
//             price: "799",
//             discounted_price: "770",
//             serve_for: "Available",
//             stock: "23",
//             measurement: "1",
//             measurement_unit_name: "pack",
//             stock_unit_name: "pack",
//             images: [],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//       {
//         id: "888",
//         name: "Belgium Chocolate Truffle Cake",
//         indicator: "1",
//         image:
//           "http://grocery.intelliatech.com/upload/images/5323-2023-02-17.png",
//         ratings: "0.0",
//         number_of_ratings: "0",
//         total_allowed_quantity: "0",
//         slug: "belgium-chocolate-truffle-cake",
//         description:
//           "<ul>\r\n<li>Cake Flavour: Belgium Chocolate Truffle</li>\r\n<li>Shape:\u00a0Square</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Chocolate</li>\r\n<li>Type of cream: Truffle</li>\r\n<li>Filling in Layers: Belgium Chocolate Truffle</li>\r\n</ul>",
//         status: "1",
//         category_name: " Cakes",
//         tax_percentage: "18",
//         price: "800",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "852",
//             product_id: "888",
//             price: "800",
//             discounted_price: "200",
//             serve_for: "Sold Out",
//             stock: "0",
//             measurement: "500",
//             measurement_unit_name: "gm",
//             stock_unit_name: "gm",
//             images: [],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//       {
//         id: "890",
//         name: "Decorated Hidden Gems Cake",
//         indicator: "1",
//         image:
//           "http://grocery.intelliatech.com/upload/images/4825-2023-02-17.jpeg",
//         ratings: "0.0",
//         number_of_ratings: "0",
//         total_allowed_quantity: "0",
//         slug: "decorated-hidden-gems-cake-1",
//         description:
//           "<ul>\r\n<li>Cake Flavor- Decorated Hidden Gems Cake</li>\r\n<li>Type of Cake- Cream Cake</li>\r\n<li>Weight- Half Kg</li>\r\n<li>Shape- Round</li>\r\n<li>Serves- 4-6 People</li>\r\n</ul>",
//         status: "1",
//         category_name: " Cakes",
//         tax_percentage: "18",
//         price: "1000",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "854",
//             product_id: "890",
//             price: "1000",
//             discounted_price: "100",
//             serve_for: "Available",
//             stock: "33",
//             measurement: "500",
//             measurement_unit_name: "gm",
//             stock_unit_name: "gm",
//             images: [],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//       {
//         id: "891",
//         name: "Choco Chip Muddy Chocolate Cake",
//         indicator: "1",
//         image:
//           "http://grocery.intelliatech.com/upload/images/3804-2023-02-17.png",
//         ratings: "0.0",
//         number_of_ratings: "0",
//         total_allowed_quantity: "0",
//         slug: "choco-chip-muddy-chocolate-cake",
//         description:
//           "<ul>\r\n<li>Cake Flavour: Chocolate</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Chocolate</li>\r\n<li>Type of Cream: Chocolate</li>\r\n<li>Filling in Layers: Chocochip</li>\r\n<li>Toppings: Chocochip &amp; Chocolate garnish</li>\r\n</ul>",
//         status: "1",
//         category_name: " Cakes",
//         tax_percentage: "18",
//         price: "1200",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "855",
//             product_id: "891",
//             price: "1200",
//             discounted_price: "300",
//             serve_for: "Sold Out",
//             stock: "0",
//             measurement: "500",
//             measurement_unit_name: "gm",
//             stock_unit_name: "gm",
//             images: [
//               "http://grocery.intelliatech.com/upload/variant_images/1676618218.9123-951.png",
//             ],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//       {
//         id: "892",
//         name: "Marble Crunch Cake",
//         indicator: "1",
//         image:
//           "http://grocery.intelliatech.com/upload/images/8672-2023-02-17.png",
//         ratings: "0.0",
//         number_of_ratings: "0",
//         total_allowed_quantity: "0",
//         slug: "marble-crunch-cake",
//         description:
//           "<ul>\r\n<li>Cake Flavour: Chocolate</li>\r\n<li>Shape: Round</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Chocolate</li>\r\n<li>Type of cream: Chocolate</li>\r\n<li>Filling in Layers: Choco Chips</li>\r\n<li>Toppings: White and Chocolate Choco chips, Chocolate,Truffle and Cherry</li>\r\n</ul>",
//         status: "1",
//         category_name: " Cakes",
//         tax_percentage: "18",
//         price: "1000",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "856",
//             product_id: "892",
//             price: "1000",
//             discounted_price: "200",
//             serve_for: "Available",
//             stock: "7",
//             measurement: "500",
//             measurement_unit_name: "gm",
//             stock_unit_name: "gm",
//             images: [
//               "http://grocery.intelliatech.com/upload/variant_images/1676618331.2981-683.png",
//             ],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//       {
//         id: "893",
//         name: "Butterscotch Flavorsome Cake",
//         indicator: "1",
//         image:
//           "http://grocery.intelliatech.com/upload/images/7838-2023-02-17.png",
//         ratings: "0.0",
//         number_of_ratings: "0",
//         total_allowed_quantity: "0",
//         slug: "butterscotch-flavorsome-cake",
//         description:
//           "<ul>\r\n<li>Cake Flavor: Butterscotch</li>\r\n<li>Shape: Round</li>\r\n<li>Type of Cake: Cream</li>\r\n<li>Type of Bread: Vanilla</li>\r\n<li>Type of cream: Vanilla</li>\r\n<li>Filling in Layers: Butterscotch</li>\r\n<li>Toppings: Butterscotch, Cherry, chocolate &amp; Choco Chip</li>\r\n</ul>",
//         status: "1",
//         category_name: " Cakes",
//         tax_percentage: "18",
//         price: "800",
//         is_favorite: false,
//         variants: [
//           {
//             type: "packet",
//             id: "857",
//             product_id: "893",
//             price: "800",
//             discounted_price: "50",
//             serve_for: "Available",
//             stock: "29",
//             measurement: "500",
//             measurement_unit_name: "gm",
//             stock_unit_name: "gm",
//             images: [
//               "http://grocery.intelliatech.com/upload/variant_images/1676618514.4521-883.png",
//             ],
//             cart_count: "0",
//             is_flash_sales: false,
//             flash_sales: [
//               {
//                 price: "",
//                 discounted_price: "",
//                 start_date: "",
//                 end_date: "",
//                 is_start: false,
//               },
//             ],
//           },
//         ],
//       },
//     ],
//   }

